[project]
name = "connect-4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "ipdb>=0.13.13",
    "loguru>=0.7.3",
    "numpy>=2.0.2",
    "rich>=14.1.0",
]
